--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/STCraftNetwork/AuctionHouse
build-by-default: true
branches:
- main
projects:
  AuctionHouse:
    libs:
      - src: muqsit\invmenu
        version: ^4.6.5
    path: ""
...
